[dev]
  command = "yarn dev"
  framework = "svelte"
  functionsPort = 8008
[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[build]
  functions = "functions"
  publish = "dist"